name: Test Runner
on: workflow_dispatch  # Allows manual trigger

jobs:
  test:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - uses: actions/checkout@v3
      - name: Test Runner
        run: |
          echo "Runner is working!"
          echo "Running on host: $(hostname)"
          echo "OS Information:"
          cat /etc/os-release
